-- CreateTable
CREATE TABLE `ADMIN_MASTER` (
    `ADMIN_ID` VARCHAR(25) NOT NULL,
    `ADMIN_EMAIL` VARCHAR(200) NOT NULL,
    `ADMIN_NAME` VARCHAR(191) NULL,
    `ADMIN_PASSWORD` VARCHAR(191) NOT NULL,
    `ADMIN_STATUS` TINYINT NOT NULL,
    `ADMIN_ROLE` ENUM('staff', 'super_admin') NOT NULL DEFAULT 'staff',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `ADMIN_MASTER_ADMIN_EMAIL_key`(`ADMIN_EMAIL`),
    PRIMARY KEY (`ADMIN_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `USER_MASTER` (
    `USER_ID` VARCHAR(25) NOT NULL,
    `USER_EMAIL` VARCHAR(200) NOT NULL,
    `USER_NAME` VARCHAR(191) NULL,
    `USER_PASSWORD` VARCHAR(191) NOT NULL,
    `USER_STATUS` TINYINT NOT NULL,
    `USER_PHONENUMBER` VARCHAR(20) NULL,
    `USER_POINT` INTEGER NULL DEFAULT 0,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `USER_MASTER_USER_EMAIL_key`(`USER_EMAIL`),
    UNIQUE INDEX `USER_MASTER_USER_PHONENUMBER_key`(`USER_PHONENUMBER`),
    PRIMARY KEY (`USER_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `USER_ADDRESS` (
    `ADDRESS_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ADDRESS_STREET` VARCHAR(191) NOT NULL,
    `ADDRESS_CITY` VARCHAR(191) NOT NULL,
    `ADDRESS_DESC` VARCHAR(191) NOT NULL,
    `ADDRESS_POSTCODE` VARCHAR(191) NOT NULL,
    `ADDRESS_STATUS` TINYINT NOT NULL,
    `USER_ID` VARCHAR(25) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `USER_ADDRESS_USER_ID_idx`(`USER_ID`),
    PRIMARY KEY (`ADDRESS_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PRODUCT_MASTER` (
    `PRODUCT_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PRODUCT_NAME` VARCHAR(191) NOT NULL,
    `PRODUCT_SLUG` VARCHAR(250) NOT NULL,
    `PRODUCT_DESC` TEXT NULL,
    `PRODUCT_STATUS` TINYINT NOT NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,

    UNIQUE INDEX `PRODUCT_MASTER_PRODUCT_SLUG_key`(`PRODUCT_SLUG`),
    PRIMARY KEY (`PRODUCT_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PRODUCT_VARIANT` (
    `PRODUCT_VARIANT_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PRODUCT_ID` INTEGER NOT NULL,
    `SIZE_ID` INTEGER NULL,
    `COLOR_ID` INTEGER NULL,
    `SKU` VARCHAR(100) NOT NULL,
    `PRICE` DECIMAL(15, 2) NOT NULL,
    `COMPARE_PRICE` DECIMAL(15, 2) NULL,
    `STATUS` TINYINT NOT NULL,

    UNIQUE INDEX `PRODUCT_VARIANT_SKU_key`(`SKU`),
    INDEX `PRODUCT_VARIANT_PRODUCT_ID_idx`(`PRODUCT_ID`),
    INDEX `PRODUCT_VARIANT_SIZE_ID_idx`(`SIZE_ID`),
    INDEX `PRODUCT_VARIANT_COLOR_ID_idx`(`COLOR_ID`),
    PRIMARY KEY (`PRODUCT_VARIANT_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SIZE` (
    `SIZE_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `SIZE_NAME` VARCHAR(50) NOT NULL,
    `SIZE_ORDER` INTEGER NOT NULL DEFAULT 0,
    `STATUS` TINYINT NOT NULL,

    PRIMARY KEY (`SIZE_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `COLOR` (
    `COLOR_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `COLOR_NAME` VARCHAR(50) NOT NULL,
    `COLOR_CODE` VARCHAR(20) NULL,
    `STATUS` TINYINT NOT NULL,

    PRIMARY KEY (`COLOR_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `INVENTORY` (
    `INVENTORY_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `VARIANT_ID` INTEGER NOT NULL,
    `STOCK` INTEGER NOT NULL DEFAULT 0,
    `RESERVED` INTEGER NOT NULL DEFAULT 0,

    UNIQUE INDEX `INVENTORY_VARIANT_ID_key`(`VARIANT_ID`),
    PRIMARY KEY (`INVENTORY_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CART` (
    `CART_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `USER_ID` VARCHAR(25) NOT NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,

    UNIQUE INDEX `CART_USER_ID_key`(`USER_ID`),
    PRIMARY KEY (`CART_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CART_ITEM` (
    `CART_ITEM_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `CART_ID` INTEGER NOT NULL,
    `VARIANT_ID` INTEGER NOT NULL,
    `QUANTITY` INTEGER NOT NULL,

    UNIQUE INDEX `CART_ITEM_CART_ID_VARIANT_ID_key`(`CART_ID`, `VARIANT_ID`),
    PRIMARY KEY (`CART_ITEM_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ORDER` (
    `ORDER_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `USER_ID` VARCHAR(25) NOT NULL,
    `ORDER_NUMBER` VARCHAR(50) NOT NULL,
    `SHIPPING_NAME` VARCHAR(150) NOT NULL,
    `SHIPPING_STREET` VARCHAR(255) NOT NULL,
    `SHIPPING_CITY` VARCHAR(100) NOT NULL,
    `SHIPPING_DESC` TEXT NULL,
    `SHIPPING_POSTCODE` VARCHAR(10) NOT NULL,
    `SUBTOTAL` DECIMAL(15, 2) NOT NULL,
    `SHIPPING_COST` DECIMAL(15, 2) NOT NULL,
    `DISCOUNT` DECIMAL(15, 2) NOT NULL,
    `GRAND_TOTAL` DECIMAL(15, 2) NOT NULL,
    `STATUS` ENUM('pending', 'waiting_payment', 'paid', 'processing', 'shipped', 'delivered', 'completed', 'cancelled', 'expired') NOT NULL DEFAULT 'pending',
    `SHIPPING_TRACKING_NUMBER` VARCHAR(191) NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,

    UNIQUE INDEX `ORDER_ORDER_NUMBER_key`(`ORDER_NUMBER`),
    INDEX `ORDER_USER_ID_idx`(`USER_ID`),
    PRIMARY KEY (`ORDER_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ORDER_ITEM` (
    `ORDER_ITEM_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ORDER_ID` INTEGER NOT NULL,
    `VARIANT_ID` INTEGER NOT NULL,
    `PRODUCT_NAME` VARCHAR(200) NOT NULL,
    `SKU` VARCHAR(100) NOT NULL,
    `PRICE` DECIMAL(15, 2) NOT NULL,
    `QUANTITY` INTEGER NOT NULL,
    `SUBTOTAL` DECIMAL(15, 2) NOT NULL,

    INDEX `ORDER_ITEM_ORDER_ID_idx`(`ORDER_ID`),
    INDEX `ORDER_ITEM_VARIANT_ID_idx`(`VARIANT_ID`),
    PRIMARY KEY (`ORDER_ITEM_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PAYMENT` (
    `PAYMENT_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ORDER_ID` INTEGER NOT NULL,
    `PAYMENT_METHOD` ENUM('bank_transfer', 'qris', 'e_wallet', 'cod') NOT NULL,
    `PAYMENT_STATUS` ENUM('pending', 'processing', 'paid', 'failed', 'expired', 'cancelled', 'refunded') NOT NULL DEFAULT 'pending',
    `PAYMENT_AMOUNT` DECIMAL(15, 2) NOT NULL,
    `PAYMENT_REFERENCE` VARCHAR(150) NULL,
    `PAID_AT` DATETIME(3) NULL,
    `EXPIRED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,

    INDEX `PAYMENT_PAYMENT_STATUS_idx`(`PAYMENT_STATUS`),
    INDEX `PAYMENT_PAYMENT_REFERENCE_idx`(`PAYMENT_REFERENCE`),
    PRIMARY KEY (`PAYMENT_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CATEGORY` (
    `CATEGORY_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `CATEGORY_NAME` VARCHAR(100) NOT NULL,
    `CATEGORY_SLUG` VARCHAR(150) NOT NULL,
    `STATUS` TINYINT NOT NULL,

    UNIQUE INDEX `CATEGORY_CATEGORY_SLUG_key`(`CATEGORY_SLUG`),
    PRIMARY KEY (`CATEGORY_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PRODUCT_CATEGORY` (
    `PRODUCT_ID` INTEGER NOT NULL,
    `CATEGORY_ID` INTEGER NOT NULL,

    PRIMARY KEY (`PRODUCT_ID`, `CATEGORY_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PRODUCT_IMAGE` (
    `IMAGE_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PRODUCT_ID` INTEGER NOT NULL,
    `IMAGE_URL` VARCHAR(500) NOT NULL,
    `SORT_ORDER` INTEGER NOT NULL DEFAULT 0,
    `IS_PRIMARY` BOOLEAN NOT NULL DEFAULT false,

    INDEX `PRODUCT_IMAGE_PRODUCT_ID_idx`(`PRODUCT_ID`),
    PRIMARY KEY (`IMAGE_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `INVENTORY_TRANSACTION` (
    `INVENTORY_TRANSACTION_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `VARIANT_ID` INTEGER NOT NULL,
    `TYPE` ENUM('restock', 'reserve', 'release', 'sale', 'return', 'adjustment') NOT NULL,
    `QUANTITY` INTEGER NOT NULL,
    `REFERENCE` VARCHAR(100) NULL,
    `NOTE` VARCHAR(255) NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `INVENTORY_TRANSACTION_VARIANT_ID_idx`(`VARIANT_ID`),
    INDEX `INVENTORY_TRANSACTION_TYPE_idx`(`TYPE`),
    PRIMARY KEY (`INVENTORY_TRANSACTION_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `INFORMATION_STATUS` (
    `STATUS_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TABLE_NAME` VARCHAR(100) NOT NULL,
    `STATUS_VALUE` VARCHAR(50) NOT NULL,
    `STATUS_DESC` TEXT NULL,

    PRIMARY KEY (`STATUS_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `LOGS_TRANSACTION` (
    `SZLOGID` VARCHAR(50) NOT NULL,
    `SZLOGTYPE` VARCHAR(50) NOT NULL,
    `SZLOGDESC` TEXT NULL,
    `SZLOGDATA` TEXT NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`SZLOGID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `LOGS_ACTIVITY` (
    `SZLOGID` VARCHAR(50) NOT NULL,
    `SZUSERID` VARCHAR(50) NOT NULL,
    `SZLOGDESC` TEXT NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`SZLOGID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `USER_ADDRESS` ADD CONSTRAINT `USER_ADDRESS_USER_ID_fkey` FOREIGN KEY (`USER_ID`) REFERENCES `USER_MASTER`(`USER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PRODUCT_VARIANT` ADD CONSTRAINT `PRODUCT_VARIANT_PRODUCT_ID_fkey` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCT_MASTER`(`PRODUCT_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PRODUCT_VARIANT` ADD CONSTRAINT `PRODUCT_VARIANT_SIZE_ID_fkey` FOREIGN KEY (`SIZE_ID`) REFERENCES `SIZE`(`SIZE_ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PRODUCT_VARIANT` ADD CONSTRAINT `PRODUCT_VARIANT_COLOR_ID_fkey` FOREIGN KEY (`COLOR_ID`) REFERENCES `COLOR`(`COLOR_ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `INVENTORY` ADD CONSTRAINT `INVENTORY_VARIANT_ID_fkey` FOREIGN KEY (`VARIANT_ID`) REFERENCES `PRODUCT_VARIANT`(`PRODUCT_VARIANT_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CART` ADD CONSTRAINT `CART_USER_ID_fkey` FOREIGN KEY (`USER_ID`) REFERENCES `USER_MASTER`(`USER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CART_ITEM` ADD CONSTRAINT `CART_ITEM_CART_ID_fkey` FOREIGN KEY (`CART_ID`) REFERENCES `CART`(`CART_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CART_ITEM` ADD CONSTRAINT `CART_ITEM_VARIANT_ID_fkey` FOREIGN KEY (`VARIANT_ID`) REFERENCES `PRODUCT_VARIANT`(`PRODUCT_VARIANT_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ORDER` ADD CONSTRAINT `ORDER_USER_ID_fkey` FOREIGN KEY (`USER_ID`) REFERENCES `USER_MASTER`(`USER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ORDER_ITEM` ADD CONSTRAINT `ORDER_ITEM_ORDER_ID_fkey` FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDER`(`ORDER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ORDER_ITEM` ADD CONSTRAINT `ORDER_ITEM_VARIANT_ID_fkey` FOREIGN KEY (`VARIANT_ID`) REFERENCES `PRODUCT_VARIANT`(`PRODUCT_VARIANT_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PAYMENT` ADD CONSTRAINT `PAYMENT_ORDER_ID_fkey` FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDER`(`ORDER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PRODUCT_CATEGORY` ADD CONSTRAINT `PRODUCT_CATEGORY_PRODUCT_ID_fkey` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCT_MASTER`(`PRODUCT_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PRODUCT_CATEGORY` ADD CONSTRAINT `PRODUCT_CATEGORY_CATEGORY_ID_fkey` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `CATEGORY`(`CATEGORY_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PRODUCT_IMAGE` ADD CONSTRAINT `PRODUCT_IMAGE_PRODUCT_ID_fkey` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCT_MASTER`(`PRODUCT_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `INVENTORY_TRANSACTION` ADD CONSTRAINT `INVENTORY_TRANSACTION_VARIANT_ID_fkey` FOREIGN KEY (`VARIANT_ID`) REFERENCES `PRODUCT_VARIANT`(`PRODUCT_VARIANT_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
